server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/distributed_lock?characterEncoding=utf-8&useSSL=false
    username: johnny
    password: johnny